graph TB
style A fill:#ffd996,stroke:#f09b00,stroke-width:4px
style B fill:#ffd996,stroke:#f09b00,stroke-width:4px
style C fill:#a5a5ff,stroke:#0000a5,stroke-width:4px
style D stroke:#4B1589,stroke-width:3px
style E stroke:#4B1589,stroke-width:3px
style F fill:#ffc0cb,stroke:#b40000,stroke-width:6px
style G fill:#3CB371,stroke:#006400,stroke-width:3px
style H fill:#3CB371,stroke:#006400,stroke-width:3px
  A(<b>Bioassessment data</b>)-.->|Calculate Indices| B(<b>ASCI & CSCI scores</b>)
  B-.->|Sampled May-Sep| D[<center>1. Retain <b>USGS gages</b> & <b>Bioassessment sites</b><br>that occur in same HUC12</center>]
  C(<center><b>USGS:</b><br> Download & clean gage data</center>)-.->|>10 years of data| D
  subgraph Join Spatially
  D-.->|"Assign NHD stream segment (COMID) to" <br> each <b>Bioassessment site</b> and <b>USGS gage</b>| E[<center><b>2.</b> Identify and pair <b>sites</b> with <b>USGS gages</b> <br> connected by mainstem NHD stream segments<br>less than 10 km apart with no major tributary inflows</center>]
  end
  E-->F((<center><b>STOP:</b><br> Bioassessment site not on <br>mainstem streamline<br>of USGS gage</center>))
  E--> G(Filter to Flow Data >1994 <br> to match ecological data period)
  G--> H(<center>Calculate Functional Flow Metrics & Alteration Status<br>for Boosted Regression Tree Models</center>)

